=== ollieread/game-engine-markup-language/schema/attribute.schema.json
{
  "$schema"    : "https://json-schema.org/draft/2020-12/schema",
  "$id"        : "https://example.com/schemas/attribute.schema.json",
  "title"      : "Attribute",
  "description": "Defines an attribute that an entity can possess",
  "type"       : "object",
  "properties" : {
    "name"     : {
      "type": "string"
    },
    "shortName": {
      "type": "string"
    },
    "baseValue": {
      "type": "integer"
    },
    "modifier" : {
      "oneOf": [
        {
          "$ref": "/schema/expression.schema.json"
        },
        {
          "$ref": "/schema/function-reference.schema.json"
        }
      ]
    }
  },
  "required"   : [
    "name",
    "shortName",
    "baseValue"
  ]
}

=== ollieread/game-engine-markup-language/dnd/attributes/constitution.json
{
  "$schema"  : "/schema/attribute.schema.json",
  "name"     : "Constitution",
  "shortName": "CON",
  "baseValue": 10,
  "modifier" : {
    "floor": [
      {
        "div": [
          {
            "sub": [
              {
                "var": "entity.attributes.{$shortName}.calculatedValue"
              },
              {
                "const": 10
              }
            ]
          },
          {
            "const": 2
          }
        ]
      }
    ]
  }
}

=== ollieread/game-engine-markup-language/dnd/attributes/wisdom.json
{
  "$schema"  : "/schema/attribute.schema.json",
  "name"     : "Wisdom",
  "shortName": "WIS",
  "baseValue": 10,
  "modifier" : {
    "floor": [
      {
        "div": [
          {
            "sub": [
              {
                "var": "entity.attributes.{$shortName}.calculatedValue"
              },
              {
                "const": 10
              }
            ]
          },
          {
            "const": 2
          }
        ]
      }
    ]
  }
}

=== ollieread/game-engine-markup-language/dnd/attributes/dexterity.json
{
  "$schema"  : "/schema/attribute.schema.json",
  "name"     : "Dexterity",
  "shortName": "DEX",
  "baseValue": 10,
  "modifier" : {
    "floor": [
      {
        "div": [
          {
            "sub": [
              {
                "var": "entity.attributes.{$shortName}.calculatedValue"
              },
              {
                "const": 10
              }
            ]
          },
          {
            "const": 2
          }
        ]
      }
    ]
  }
}

=== ollieread/game-engine-markup-language/dnd/attributes/charisma.json
{
  "$schema"  : "/schema/attribute.schema.json",
  "name"     : "Charisma",
  "shortName": "CHA",
  "baseValue": 10,
  "modifier" : {
    "floor": [
      {
        "div": [
          {
            "sub": [
              {
                "var": "entity.attributes.{$shortName}.calculatedValue"
              },
              {
                "const": 10
              }
            ]
          },
          {
            "const": 2
          }
        ]
      }
    ]
  }
}

=== ollieread/game-engine-markup-language/dnd/attributes/intelligence.json
{
  "$schema"  : "/schema/attribute.schema.json",
  "name"     : "Intelligence",
  "shortName": "INT",
  "baseValue": 10,
  "modifier" : {
    "floor": [
      {
        "div": [
          {
            "sub": [
              {
                "var": "entity.attributes.{$shortName}.calculatedValue"
              },
              {
                "const": 10
              }
            ]
          },
          {
            "const": 2
          }
        ]
      }
    ]
  }
}
