=== ollieread/game-engine-markup-language/schema/system.schema.json
{
  "$schema"    : "https://json-schema.org/draft/2020-12/schema",
  "$id"        : "https://geml.ollieread.com/schemas/system.schema.json",
  "title"      : "Game System",
  "description": "Defines a game system",
  "type"       : "object",
  "properties" : {
    "name"      : {
      "type": "string"
    },
    "slug"      : {
      "type"   : "string",
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "version"   : {
      "type"    : "string",
      "pattern:": "^\\d+\\.\\d+\\.\\d+$"
    },
    "attributes": {
      "type" : "array",
      "items": {
        "oneOf": [
          {
            "type"       : "string",
            "description": "A path to an attribute file"
          },
          {
            "$ref"       : "/schema/attribute.schema.json",
            "description": "An attribute object"
          }
        ]
      }
    },
    "functions": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type"       : "string",
            "description": "A path to a function file"
          },
          {
            "$ref"       : "/schema/function.schema.json",
            "description": "A function object"
          }
        ]
      }
    }
  },
  "required"   : [
    "name",
    "slug",
    "version"
  ]
}

=== ollieread/game-engine-markup-language/dnd/system.json
{
  "$schema"   : "/schema/system.schema.json",
  "name"      : "Dungeons & Dragons 5th Edition",
  "slug"      : "dnd-5e",
  "version"   : "1.0.0",
  "attributes": [
    "/attributes/strength.json",
    "/attributes/dexterity.json",
    "/attributes/constitution.json",
    "/attributes/intelligence.json",
    "/attributes/wisdom.json",
    "/attributes/charisma.json"
  ],
  "functions": [
    "/functions/modifier.json"
  ]
}
